version: '2'

services:
    generate:
        image: ssense-challenge-template
        build: .
        volumes:
            - ./data:/data
            - .:/srv/app
            - ./results:/results
        stdin_open: true
        tty: true
